### ISSUE TITLE
Refactor `getButtonIconStyles` to eliminate redundant icon styling

### ISSUE THREAD

**Issue by Fybex** [maxi-blocks/maxi-blocks#5281]
Clean `getButtonIconStyles` logic

These lines add SVG styles all the time (even when `!hasIcon`) https://github.com/maxi-blocks/maxi-blocks/blob/master/src/extensions/styles/helpers/getButtonIconStyles.js#L321-L330

For example, here's styles for default button-maxi:

part of styles which I found unnecessary:
```css
body.maxi-blocks--active .edit-post-visual-editor .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path{ stroke-width: 2;}body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xl"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="l"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="m"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="s"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xs"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path{ stroke-width: 2;}
```

full styles:
```css
body.maxi-blocks--active .edit-post-visual-editor .maxi-block.maxi-block--backend.button-maxi-73d8e040-u,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u{ justify-content: center;}body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xl"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="l"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="m"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="s"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xs"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u{ justify-content: center;}body.maxi-blocks--active .edit-post-visual-editor .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button{ border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px; text-align: center; background: var(--maxi-light-button-background-color,rgba(var(--maxi-light-color-4,255,74,23),1)); padding-top: 15px; padding-right: 36px; padding-bottom: 15px; padding-left: 36px;}body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xl"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="l"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="m"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="s"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xs"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button{ border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px; text-align: center; background: var(--maxi-light-button-background-color,rgba(var(--maxi-light-color-4,255,74,23),1)); padding-top: 15px; padding-right: 36px; padding-bottom: 15px; padding-left: 36px;}body.maxi-blocks--active .edit-post-visual-editor .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content{ color: var(--maxi-light-button-color,rgba(var(--maxi-light-color-1,255,255,255),1));}body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xl"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="l"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="m"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="s"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xs"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__content{ color: var(--maxi-light-button-color,rgba(var(--maxi-light-color-1,255,255,255),1));}body.maxi-blocks--active .edit-post-visual-editor .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path{ stroke-width: 2;}body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xl"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="l"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="m"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="s"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path,body.maxi-blocks--active .edit-post-visual-editor[maxi-blocks-responsive="xs"] .maxi-block.maxi-block--backend.button-maxi-73d8e040-u .maxi-button-block__button .maxi-button-block__icon svg path{ stroke-width: 2;}
```

So it looks to me like it's completely unnecessary and shouldn't be generated when `hasIcon` is `false`
