### ISSUE TITLE
Some selectors don't works in Advanced CSS

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5527]
### Description

Tested with nth-child
Need to check all extra selectors

### Step-by-step reproduction instructions

Create some blocks and try to use child selectors

**Comment by kyrapieterse** [comment]
Closing this as fixed / no longer reproducible on current master.

Tested locally on WP 6 using a Maxi Group block with a core Gallery block and this Advanced CSS:

```css
.wp-block-gallery .wp-block-image {
  outline: 2px solid blue !important;
}

.wp-block-gallery .wp-block-image:not(#individual-image):nth-child(4n) {
  outline: 6px solid red !important;
  opacity: 0.35 !important;
}
```

Result:
- The frontend generated the scoped Advanced CSS selector correctly.
- The gallery images received the blue outline.
- The matching `:not(...):nth-child(4n)` item received the red outline and opacity rule, as shown in the screenshot.
- `npm test -- getAdvancedCssObject --runInBand` passed.

The originally reported selector case appears to work now, so this issue can be closed.

<img width="678" height="672" alt="Image" src="https://github.com/user-attachments/assets/05669053-7573-4a11-920a-91d2c032ad68" />
